# Generated by Django 2.2.4 on 2021-04-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default=None, upload_to='images/photo/'),
            preserve_default=False,
        ),
    ]
