# Generated by Django 2.2.4 on 2021-05-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210506_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
