# Generated by Django 2.2.4 on 2021-06-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_announcement_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
