# Generated by Django 2.2.4 on 2021-06-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_photo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='slug',
        ),
        migrations.AddField(
            model_name='announcement',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
